services:
  app:
    build: .
    ports:
      - "5000:8080"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Host=db;Database=erp_db;Username=postgres;Password=postgres
    volumes:
      - ./wwwroot/uploads:/app/wwwroot/uploads # Це збереже картинки на твоєму диску
    depends_on:
      db:
        condition: service_healthy
  # База даних PostgreSQL
  db:
    image: postgres:16
    restart: always
    environment:
      POSTGRES_DB: erp_db
      POSTGRES_USER: postgres  # Змінено з admin
      POSTGRES_PASSWORD: postgres # Змінено з secret
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d erp_db"] # Тут теж міняємо на postgres
      interval: 5s
      timeout: 5s
      retries: 5